### ISSUE TITLE
Problem with login to wallet

### ISSUE THREAD

**Issue by MortyUganda** [TRRXITTE/traaittEnterpriseXTEwindows#1]
![image](https://github.com/TRRXITTE/traaittEnterpriseXTE/assets/114567024/ac982dbb-a53a-4c01-90b2-1e5db893682f)

**Comment by MortyUganda** [comment]
Hey! Are you here?

**Comment by traaitt** [comment]
try latest version and import keys / mmnemonic into wallet.

**Comment by traaitt** [comment]
https://t.me/traaitt for support
